#!/usr/bin/env node
/**
 * Generate version.ts from package.json
 * This runs before build to ensure the SDK version is always in sync
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionFilePath = path.join(__dirname, '..', 'src', 'sdk', 'version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

const content = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/generate-version.js from package.json
 */

export const SDK_VERSION = '${packageJson.version}';
`;

fs.writeFileSync(versionFilePath, content);
console.log(`Generated version.ts with SDK_VERSION = '${packageJson.version}'`);
