#!/usr/bin/env node
/**
 * Generate version.ts from package.json
 * This runs before build to ensure the SDK version is always in sync
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionFilePath = path.join(__dirname, '..', 'src', 'sdk', 'version.ts');
const androidSdkInfoPath = path.join(__dirname, '..', 'android', 'src', 'main', 'java', 'com', 'rejourney', 'RejourneySdkInfo.kt');
const androidModuleImplPath = path.join(__dirname, '..', 'android', 'src', 'main', 'java', 'com', 'rejourney', 'RejourneyModuleImpl.kt');
const iosImplPath = path.join(__dirname, '..', 'ios', 'Engine', 'RejourneyImpl.swift');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

const content = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/generate-version.js from package.json
 */

export const SDK_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, content);

function replaceInFile(filePath, pattern, replacement, label) {
  const source = fs.readFileSync(filePath, 'utf8');
  if (!pattern.test(source)) {
    throw new Error(`Failed to update ${label} in ${filePath}`);
  }

  const updated = source.replace(pattern, replacement);
  fs.writeFileSync(filePath, updated);
}

replaceInFile(
  androidSdkInfoPath,
  /(var sdkVersion: String = ")[^"]+(")/,
  `$1${version}$2`,
  'Android SDK version'
);

replaceInFile(
  androidModuleImplPath,
  /(var sdkVersion = ")[^"]+(")/,
  `$1${version}$2`,
  'Android module SDK version'
);

replaceInFile(
  iosImplPath,
  /(@objc public static var sdkVersion = ")[^"]+(")/,
  `$1${version}$2`,
  'iOS SDK version'
);

console.log(`Synced SDK version metadata to '${version}'`);
