// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/*": {
    params: {
      "*": string;
    };
  };
  "/contribute": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/terms-of-service": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/dpa": {
    params: {};
  };
  "/engineering": {
    params: {};
  };
  "/engineering/:date/:slug": {
    params: {
      "date": string;
      "slug": string;
    };
  };
  "/feed.xml": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/changelog": {
    params: {};
  };
  "/invite/accept/:token": {
    params: {
      "token": string;
    };
  };
  "/demo": {
    params: {};
  };
  "/demo/general": {
    params: {};
  };
  "/demo/general/:issueId": {
    params: {
      "issueId": string;
    };
  };
  "/demo/issues": {
    params: {};
  };
  "/demo/issues/:issueId": {
    params: {
      "issueId": string;
    };
  };
  "/demo/sessions": {
    params: {};
  };
  "/demo/sessions/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/demo/analytics/api": {
    params: {};
  };
  "/demo/stability/crashes": {
    params: {};
  };
  "/demo/stability/crashes/:projectId/:crashId": {
    params: {
      "projectId": string;
      "crashId": string;
    };
  };
  "/demo/stability/anrs": {
    params: {};
  };
  "/demo/stability/anrs/:projectId/:anrId": {
    params: {
      "projectId": string;
      "anrId": string;
    };
  };
  "/demo/stability/errors": {
    params: {};
  };
  "/demo/stability/errors/:projectId/:errorId": {
    params: {
      "projectId": string;
      "errorId": string;
    };
  };
  "/demo/analytics/journeys": {
    params: {};
  };
  "/demo/analytics/devices": {
    params: {};
  };
  "/demo/analytics/geo": {
    params: {};
  };
  "/demo/alerts/emails": {
    params: {};
  };
  "/demo/team": {
    params: {};
  };
  "/demo/warehouse": {
    params: {};
  };
  "/demo/billing": {
    params: {};
  };
  "/demo/billing/return": {
    params: {};
  };
  "/demo/account": {
    params: {};
  };
  "/demo/settings/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/demo/search": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/general": {
    params: {};
  };
  "/dashboard/general/:issueId": {
    params: {
      "issueId": string;
    };
  };
  "/dashboard/issues": {
    params: {};
  };
  "/dashboard/issues/:issueId": {
    params: {
      "issueId": string;
    };
  };
  "/dashboard/sessions": {
    params: {};
  };
  "/dashboard/sessions/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/dashboard/analytics/api": {
    params: {};
  };
  "/dashboard/stability/crashes": {
    params: {};
  };
  "/dashboard/stability/crashes/:projectId/:crashId": {
    params: {
      "projectId": string;
      "crashId": string;
    };
  };
  "/dashboard/stability/anrs": {
    params: {};
  };
  "/dashboard/stability/anrs/:projectId/:anrId": {
    params: {
      "projectId": string;
      "anrId": string;
    };
  };
  "/dashboard/stability/errors": {
    params: {};
  };
  "/dashboard/stability/errors/:projectId/:errorId": {
    params: {
      "projectId": string;
      "errorId": string;
    };
  };
  "/dashboard/analytics/journeys": {
    params: {};
  };
  "/dashboard/analytics/devices": {
    params: {};
  };
  "/dashboard/analytics/geo": {
    params: {};
  };
  "/dashboard/alerts/emails": {
    params: {};
  };
  "/dashboard/team": {
    params: {};
  };
  "/dashboard/warehouse": {
    params: {};
  };
  "/dashboard/billing": {
    params: {};
  };
  "/dashboard/billing/return": {
    params: {};
  };
  "/dashboard/account": {
    params: {};
  };
  "/dashboard/settings/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/dashboard/search": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs" | "/docs/*" | "/contribute" | "/pricing" | "/terms-of-service" | "/privacy-policy" | "/dpa" | "/engineering" | "/engineering/:date/:slug" | "/feed.xml" | "/login" | "/changelog" | "/invite/accept/:token" | "/demo" | "/demo/general" | "/demo/general/:issueId" | "/demo/issues" | "/demo/issues/:issueId" | "/demo/sessions" | "/demo/sessions/:sessionId" | "/demo/analytics/api" | "/demo/stability/crashes" | "/demo/stability/crashes/:projectId/:crashId" | "/demo/stability/anrs" | "/demo/stability/anrs/:projectId/:anrId" | "/demo/stability/errors" | "/demo/stability/errors/:projectId/:errorId" | "/demo/analytics/journeys" | "/demo/analytics/devices" | "/demo/analytics/geo" | "/demo/alerts/emails" | "/demo/team" | "/demo/warehouse" | "/demo/billing" | "/demo/billing/return" | "/demo/account" | "/demo/settings/:projectId" | "/demo/search" | "/dashboard" | "/dashboard/general" | "/dashboard/general/:issueId" | "/dashboard/issues" | "/dashboard/issues/:issueId" | "/dashboard/sessions" | "/dashboard/sessions/:sessionId" | "/dashboard/analytics/api" | "/dashboard/stability/crashes" | "/dashboard/stability/crashes/:projectId/:crashId" | "/dashboard/stability/anrs" | "/dashboard/stability/anrs/:projectId/:anrId" | "/dashboard/stability/errors" | "/dashboard/stability/errors/:projectId/:errorId" | "/dashboard/analytics/journeys" | "/dashboard/analytics/devices" | "/dashboard/analytics/geo" | "/dashboard/alerts/emails" | "/dashboard/team" | "/dashboard/warehouse" | "/dashboard/billing" | "/dashboard/billing/return" | "/dashboard/account" | "/dashboard/settings/:projectId" | "/dashboard/search";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/docs.$slug.tsx": {
    id: "routes/docs.$slug";
    page: "/docs/*";
  };
  "routes/contribute.tsx": {
    id: "routes/contribute";
    page: "/contribute";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/terms-of-service.tsx": {
    id: "routes/terms-of-service";
    page: "/terms-of-service";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/dpa.tsx": {
    id: "routes/dpa";
    page: "/dpa";
  };
  "routes/engineering.list.tsx": {
    id: "routes/engineering.list";
    page: "/engineering";
  };
  "routes/engineering.article.tsx": {
    id: "routes/engineering.article";
    page: "/engineering/:date/:slug";
  };
  "routes/feed.xml.tsx": {
    id: "routes/feed.xml";
    page: "/feed.xml";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/changelog.tsx": {
    id: "routes/changelog";
    page: "/changelog";
  };
  "routes/invite.accept.$token.tsx": {
    id: "routes/invite.accept.$token";
    page: "/invite/accept/:token";
  };
  "routes/_demo.tsx": {
    id: "routes/_demo";
    page: "/demo" | "/demo/general" | "/demo/general/:issueId" | "/demo/issues" | "/demo/issues/:issueId" | "/demo/sessions" | "/demo/sessions/:sessionId" | "/demo/analytics/api" | "/demo/stability/crashes" | "/demo/stability/crashes/:projectId/:crashId" | "/demo/stability/anrs" | "/demo/stability/anrs/:projectId/:anrId" | "/demo/stability/errors" | "/demo/stability/errors/:projectId/:errorId" | "/demo/analytics/journeys" | "/demo/analytics/devices" | "/demo/analytics/geo" | "/demo/alerts/emails" | "/demo/team" | "/demo/warehouse" | "/demo/billing" | "/demo/billing/return" | "/demo/account" | "/demo/settings/:projectId" | "/demo/search";
  };
  "routes/_demo._index.tsx": {
    id: "routes/_demo._index";
    page: "/demo";
  };
  "routes/_demo.general.tsx": {
    id: "routes/_demo.general";
    page: "/demo/general";
  };
  "routes/_demo.general.$issueId.tsx": {
    id: "routes/_demo.general.$issueId";
    page: "/demo/general/:issueId";
  };
  "routes/_demo.issues.tsx": {
    id: "routes/_demo.issues";
    page: "/demo/issues";
  };
  "routes/_demo.issues.$issueId.tsx": {
    id: "routes/_demo.issues.$issueId";
    page: "/demo/issues/:issueId";
  };
  "routes/_demo.sessions.tsx": {
    id: "routes/_demo.sessions";
    page: "/demo/sessions";
  };
  "routes/_demo.sessions.$sessionId.tsx": {
    id: "routes/_demo.sessions.$sessionId";
    page: "/demo/sessions/:sessionId";
  };
  "routes/_demo.analytics.api.tsx": {
    id: "routes/_demo.analytics.api";
    page: "/demo/analytics/api";
  };
  "routes/_demo.stability.crashes.tsx": {
    id: "routes/_demo.stability.crashes";
    page: "/demo/stability/crashes";
  };
  "routes/_demo.stability.crashes.$projectId.$crashId.tsx": {
    id: "routes/_demo.stability.crashes.$projectId.$crashId";
    page: "/demo/stability/crashes/:projectId/:crashId";
  };
  "routes/_demo.stability.anrs.tsx": {
    id: "routes/_demo.stability.anrs";
    page: "/demo/stability/anrs";
  };
  "routes/_demo.stability.anrs.$projectId.$anrId.tsx": {
    id: "routes/_demo.stability.anrs.$projectId.$anrId";
    page: "/demo/stability/anrs/:projectId/:anrId";
  };
  "routes/_demo.stability.errors.tsx": {
    id: "routes/_demo.stability.errors";
    page: "/demo/stability/errors";
  };
  "routes/_demo.stability.errors.$projectId.$errorId.tsx": {
    id: "routes/_demo.stability.errors.$projectId.$errorId";
    page: "/demo/stability/errors/:projectId/:errorId";
  };
  "routes/_demo.analytics.journeys.tsx": {
    id: "routes/_demo.analytics.journeys";
    page: "/demo/analytics/journeys";
  };
  "routes/_demo.analytics.devices.tsx": {
    id: "routes/_demo.analytics.devices";
    page: "/demo/analytics/devices";
  };
  "routes/_demo.analytics.geo.tsx": {
    id: "routes/_demo.analytics.geo";
    page: "/demo/analytics/geo";
  };
  "routes/_demo.alerts.emails.tsx": {
    id: "routes/_demo.alerts.emails";
    page: "/demo/alerts/emails";
  };
  "routes/_demo.team.tsx": {
    id: "routes/_demo.team";
    page: "/demo/team";
  };
  "routes/_demo.warehouse.tsx": {
    id: "routes/_demo.warehouse";
    page: "/demo/warehouse";
  };
  "routes/_demo.billing.tsx": {
    id: "routes/_demo.billing";
    page: "/demo/billing";
  };
  "routes/_demo.billing.return.tsx": {
    id: "routes/_demo.billing.return";
    page: "/demo/billing/return";
  };
  "routes/_demo.account.tsx": {
    id: "routes/_demo.account";
    page: "/demo/account";
  };
  "routes/_demo.settings.$projectId.tsx": {
    id: "routes/_demo.settings.$projectId";
    page: "/demo/settings/:projectId";
  };
  "routes/_demo.search.tsx": {
    id: "routes/_demo.search";
    page: "/demo/search";
  };
  "routes/_dashboard.tsx": {
    id: "routes/_dashboard";
    page: "/dashboard" | "/dashboard/general" | "/dashboard/general/:issueId" | "/dashboard/issues" | "/dashboard/issues/:issueId" | "/dashboard/sessions" | "/dashboard/sessions/:sessionId" | "/dashboard/analytics/api" | "/dashboard/stability/crashes" | "/dashboard/stability/crashes/:projectId/:crashId" | "/dashboard/stability/anrs" | "/dashboard/stability/anrs/:projectId/:anrId" | "/dashboard/stability/errors" | "/dashboard/stability/errors/:projectId/:errorId" | "/dashboard/analytics/journeys" | "/dashboard/analytics/devices" | "/dashboard/analytics/geo" | "/dashboard/alerts/emails" | "/dashboard/team" | "/dashboard/warehouse" | "/dashboard/billing" | "/dashboard/billing/return" | "/dashboard/account" | "/dashboard/settings/:projectId" | "/dashboard/search";
  };
  "routes/_dashboard._index.tsx": {
    id: "routes/_dashboard._index";
    page: "/dashboard";
  };
  "routes/_dashboard.general.tsx": {
    id: "routes/_dashboard.general";
    page: "/dashboard/general";
  };
  "routes/_dashboard.general.$issueId.tsx": {
    id: "routes/_dashboard.general.$issueId";
    page: "/dashboard/general/:issueId";
  };
  "routes/_dashboard.issues.tsx": {
    id: "routes/_dashboard.issues";
    page: "/dashboard/issues";
  };
  "routes/_dashboard.issues.$issueId.tsx": {
    id: "routes/_dashboard.issues.$issueId";
    page: "/dashboard/issues/:issueId";
  };
  "routes/_dashboard.sessions.tsx": {
    id: "routes/_dashboard.sessions";
    page: "/dashboard/sessions";
  };
  "routes/_dashboard.sessions.$sessionId.tsx": {
    id: "routes/_dashboard.sessions.$sessionId";
    page: "/dashboard/sessions/:sessionId";
  };
  "routes/_dashboard.analytics.api.tsx": {
    id: "routes/_dashboard.analytics.api";
    page: "/dashboard/analytics/api";
  };
  "routes/_dashboard.stability.crashes.tsx": {
    id: "routes/_dashboard.stability.crashes";
    page: "/dashboard/stability/crashes";
  };
  "routes/_dashboard.stability.crashes.$projectId.$crashId.tsx": {
    id: "routes/_dashboard.stability.crashes.$projectId.$crashId";
    page: "/dashboard/stability/crashes/:projectId/:crashId";
  };
  "routes/_dashboard.stability.anrs.tsx": {
    id: "routes/_dashboard.stability.anrs";
    page: "/dashboard/stability/anrs";
  };
  "routes/_dashboard.stability.anrs.$projectId.$anrId.tsx": {
    id: "routes/_dashboard.stability.anrs.$projectId.$anrId";
    page: "/dashboard/stability/anrs/:projectId/:anrId";
  };
  "routes/_dashboard.stability.errors.tsx": {
    id: "routes/_dashboard.stability.errors";
    page: "/dashboard/stability/errors";
  };
  "routes/_dashboard.stability.errors.$projectId.$errorId.tsx": {
    id: "routes/_dashboard.stability.errors.$projectId.$errorId";
    page: "/dashboard/stability/errors/:projectId/:errorId";
  };
  "routes/_dashboard.analytics.journeys.tsx": {
    id: "routes/_dashboard.analytics.journeys";
    page: "/dashboard/analytics/journeys";
  };
  "routes/_dashboard.analytics.devices.tsx": {
    id: "routes/_dashboard.analytics.devices";
    page: "/dashboard/analytics/devices";
  };
  "routes/_dashboard.analytics.geo.tsx": {
    id: "routes/_dashboard.analytics.geo";
    page: "/dashboard/analytics/geo";
  };
  "routes/_dashboard.alerts.emails.tsx": {
    id: "routes/_dashboard.alerts.emails";
    page: "/dashboard/alerts/emails";
  };
  "routes/_dashboard.team.tsx": {
    id: "routes/_dashboard.team";
    page: "/dashboard/team";
  };
  "routes/_dashboard.warehouse.tsx": {
    id: "routes/_dashboard.warehouse";
    page: "/dashboard/warehouse";
  };
  "routes/_dashboard.billing.tsx": {
    id: "routes/_dashboard.billing";
    page: "/dashboard/billing";
  };
  "routes/_dashboard.billing.return.tsx": {
    id: "routes/_dashboard.billing.return";
    page: "/dashboard/billing/return";
  };
  "routes/_dashboard.account.tsx": {
    id: "routes/_dashboard.account";
    page: "/dashboard/account";
  };
  "routes/_dashboard.settings.$projectId.tsx": {
    id: "routes/_dashboard.settings.$projectId";
    page: "/dashboard/settings/:projectId";
  };
  "routes/_dashboard.search.tsx": {
    id: "routes/_dashboard.search";
    page: "/dashboard/search";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
  "routes/docs.$slug": typeof import("./app/routes/docs.$slug.tsx");
  "routes/contribute": typeof import("./app/routes/contribute.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/terms-of-service": typeof import("./app/routes/terms-of-service.tsx");
  "routes/privacy-policy": typeof import("./app/routes/privacy-policy.tsx");
  "routes/dpa": typeof import("./app/routes/dpa.tsx");
  "routes/engineering.list": typeof import("./app/routes/engineering.list.tsx");
  "routes/engineering.article": typeof import("./app/routes/engineering.article.tsx");
  "routes/feed.xml": typeof import("./app/routes/feed.xml.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/changelog": typeof import("./app/routes/changelog.tsx");
  "routes/invite.accept.$token": typeof import("./app/routes/invite.accept.$token.tsx");
  "routes/_demo": typeof import("./app/routes/_demo.tsx");
  "routes/_demo._index": typeof import("./app/routes/_demo._index.tsx");
  "routes/_demo.general": typeof import("./app/routes/_demo.general.tsx");
  "routes/_demo.general.$issueId": typeof import("./app/routes/_demo.general.$issueId.tsx");
  "routes/_demo.issues": typeof import("./app/routes/_demo.issues.tsx");
  "routes/_demo.issues.$issueId": typeof import("./app/routes/_demo.issues.$issueId.tsx");
  "routes/_demo.sessions": typeof import("./app/routes/_demo.sessions.tsx");
  "routes/_demo.sessions.$sessionId": typeof import("./app/routes/_demo.sessions.$sessionId.tsx");
  "routes/_demo.analytics.api": typeof import("./app/routes/_demo.analytics.api.tsx");
  "routes/_demo.stability.crashes": typeof import("./app/routes/_demo.stability.crashes.tsx");
  "routes/_demo.stability.crashes.$projectId.$crashId": typeof import("./app/routes/_demo.stability.crashes.$projectId.$crashId.tsx");
  "routes/_demo.stability.anrs": typeof import("./app/routes/_demo.stability.anrs.tsx");
  "routes/_demo.stability.anrs.$projectId.$anrId": typeof import("./app/routes/_demo.stability.anrs.$projectId.$anrId.tsx");
  "routes/_demo.stability.errors": typeof import("./app/routes/_demo.stability.errors.tsx");
  "routes/_demo.stability.errors.$projectId.$errorId": typeof import("./app/routes/_demo.stability.errors.$projectId.$errorId.tsx");
  "routes/_demo.analytics.journeys": typeof import("./app/routes/_demo.analytics.journeys.tsx");
  "routes/_demo.analytics.devices": typeof import("./app/routes/_demo.analytics.devices.tsx");
  "routes/_demo.analytics.geo": typeof import("./app/routes/_demo.analytics.geo.tsx");
  "routes/_demo.alerts.emails": typeof import("./app/routes/_demo.alerts.emails.tsx");
  "routes/_demo.team": typeof import("./app/routes/_demo.team.tsx");
  "routes/_demo.warehouse": typeof import("./app/routes/_demo.warehouse.tsx");
  "routes/_demo.billing": typeof import("./app/routes/_demo.billing.tsx");
  "routes/_demo.billing.return": typeof import("./app/routes/_demo.billing.return.tsx");
  "routes/_demo.account": typeof import("./app/routes/_demo.account.tsx");
  "routes/_demo.settings.$projectId": typeof import("./app/routes/_demo.settings.$projectId.tsx");
  "routes/_demo.search": typeof import("./app/routes/_demo.search.tsx");
  "routes/_dashboard": typeof import("./app/routes/_dashboard.tsx");
  "routes/_dashboard._index": typeof import("./app/routes/_dashboard._index.tsx");
  "routes/_dashboard.general": typeof import("./app/routes/_dashboard.general.tsx");
  "routes/_dashboard.general.$issueId": typeof import("./app/routes/_dashboard.general.$issueId.tsx");
  "routes/_dashboard.issues": typeof import("./app/routes/_dashboard.issues.tsx");
  "routes/_dashboard.issues.$issueId": typeof import("./app/routes/_dashboard.issues.$issueId.tsx");
  "routes/_dashboard.sessions": typeof import("./app/routes/_dashboard.sessions.tsx");
  "routes/_dashboard.sessions.$sessionId": typeof import("./app/routes/_dashboard.sessions.$sessionId.tsx");
  "routes/_dashboard.analytics.api": typeof import("./app/routes/_dashboard.analytics.api.tsx");
  "routes/_dashboard.stability.crashes": typeof import("./app/routes/_dashboard.stability.crashes.tsx");
  "routes/_dashboard.stability.crashes.$projectId.$crashId": typeof import("./app/routes/_dashboard.stability.crashes.$projectId.$crashId.tsx");
  "routes/_dashboard.stability.anrs": typeof import("./app/routes/_dashboard.stability.anrs.tsx");
  "routes/_dashboard.stability.anrs.$projectId.$anrId": typeof import("./app/routes/_dashboard.stability.anrs.$projectId.$anrId.tsx");
  "routes/_dashboard.stability.errors": typeof import("./app/routes/_dashboard.stability.errors.tsx");
  "routes/_dashboard.stability.errors.$projectId.$errorId": typeof import("./app/routes/_dashboard.stability.errors.$projectId.$errorId.tsx");
  "routes/_dashboard.analytics.journeys": typeof import("./app/routes/_dashboard.analytics.journeys.tsx");
  "routes/_dashboard.analytics.devices": typeof import("./app/routes/_dashboard.analytics.devices.tsx");
  "routes/_dashboard.analytics.geo": typeof import("./app/routes/_dashboard.analytics.geo.tsx");
  "routes/_dashboard.alerts.emails": typeof import("./app/routes/_dashboard.alerts.emails.tsx");
  "routes/_dashboard.team": typeof import("./app/routes/_dashboard.team.tsx");
  "routes/_dashboard.warehouse": typeof import("./app/routes/_dashboard.warehouse.tsx");
  "routes/_dashboard.billing": typeof import("./app/routes/_dashboard.billing.tsx");
  "routes/_dashboard.billing.return": typeof import("./app/routes/_dashboard.billing.return.tsx");
  "routes/_dashboard.account": typeof import("./app/routes/_dashboard.account.tsx");
  "routes/_dashboard.settings.$projectId": typeof import("./app/routes/_dashboard.settings.$projectId.tsx");
  "routes/_dashboard.search": typeof import("./app/routes/_dashboard.search.tsx");
};