---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app-rw
  namespace: rejourney
  labels:
    app.kubernetes.io/part-of: rejourney
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app-ro
  namespace: rejourney
  labels:
    app.kubernetes.io/part-of: rejourney
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: replica

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app-r
  namespace: rejourney
  labels:
    app.kubernetes.io/part-of: rejourney
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/podRole: instance
