import type { Article } from "~/shared/data/engineeringTypes";
import type { DocMetadata } from "~/shared/lib/docsConfig";
import {
  type MarketingLocale,
  type MarketingLocaleCode,
  MARKETING_LOCALES,
} from "~/shared/lib/internationalMarketing";

type ContentLocaleCopy = {
  docsIndexTitle: string;
  docsIndexDescription: string;
  docsTitleSuffix: string;
  docsSiteName: string;
  docsBreadcrumb: string;
  docsAiHeading: string;
  docsCopyIntegrationPrompt: string;
  docsCopied: string;
  docsCopyCode: string;
  docsCopyCodeTitle: string;
  docsCopyCommandTitle: string;
  docsNavGettingStarted: string;
  docsNavInstallation: string;
  docsNavBasicSetup: string;
  docsNavRouteTracking: string;
  docsNavUserIdentification: string;
  docsNavCustomEvents: string;
  docsNavMetadata: string;
  docsNavPrivacyControls: string;
  documentationNotFoundTitle: string;
  documentationNotFoundHeading: string;
  documentationNotFoundCopy: string;
  docDefaultDescription: (title: string) => string;
  docKeywords: string[];
  engineeringMetaTitle: string;
  engineeringMetaDescription: string;
  engineeringCollectionName: string;
  engineeringFromTeam: string;
  engineeringHeading: string;
  engineeringIntro: string;
  readArticleLabel: (title: string) => string;
  articleMetaTitleSuffix: string;
  articleDefaultDescription: (title: string, keyword: string) => string;
  backToEngineering: string;
  authorHeading: string;
  engineeringTeamLabel: string;
  viewLinkedIn: string;
  viewGitHub: string;
  readTime: (minutes: string) => string;
  pricing: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string[];
    ogTitle: string;
    ogDescription: string;
    twitterTitle: string;
    pageName: string;
    ariaLabel: string;
    heading: string;
    intro: string;
    contactEyebrow: string;
    contactHeading: string;
    copied: string;
    contactEmail: string;
    emailCopiedToast: string;
    planDescriptions: Record<string, string>;
    sharedFeatures: string[];
    popular: string;
    perMonth: string;
    perYear: string;
    sessionsPerMonth: (sessions: string) => string;
    replayRetention: (retention: string) => string;
    startFree: string;
    getStarted: string;
    enterpriseEyebrow: string;
    enterpriseHeading: (sessions: string) => string;
    enterpriseCopy: string;
    contact: string;
    comparisonTitle: string;
    comparisonSubtitle: string;
    sessionsPerMonthLabel: string;
    monthlySessionsAriaLabel: string;
    rejourneyPlanLabel: (plan: string, isCustom: boolean) => string;
    posthogEstimate: string;
    sentryEstimate: string;
    selfHostedEyebrow: string;
    selfHostedHeading: string;
    selfHostedCopy: string;
    viewSource: string;
  };
};

const englishContentCopy: ContentLocaleCopy = {
  docsIndexTitle: "Web & Mobile SDK Documentation - Rejourney",
  docsIndexDescription:
    "Rejourney documentation for web and mobile apps, including the browser SDK, React Native, Swift iOS, Expo, self-hosting, and architecture guides.",
  docsTitleSuffix: "Rejourney Documentation",
  docsSiteName: "Rejourney Documentation",
  docsBreadcrumb: "Docs",
  docsAiHeading: "Use AI to integrate faster",
  docsCopyIntegrationPrompt: "Copy Integration Prompt",
  docsCopied: "Copied!",
  docsCopyCode: "Copy",
  docsCopyCodeTitle: "Copy code",
  docsCopyCommandTitle: "Copy command",
  docsNavGettingStarted: "Getting Started",
  docsNavInstallation: "Installation",
  docsNavBasicSetup: "Basic Setup",
  docsNavRouteTracking: "Route Tracking",
  docsNavUserIdentification: "User Identification",
  docsNavCustomEvents: "Custom Events",
  docsNavMetadata: "Metadata",
  docsNavPrivacyControls: "Privacy Controls",
  documentationNotFoundTitle: "Documentation Not Found - Rejourney",
  documentationNotFoundHeading: "Documentation Not Found",
  documentationNotFoundCopy: "The requested documentation page could not be found.",
  docDefaultDescription: (title) =>
    `${title} documentation for Rejourney's open-source web and mobile observability platform.`,
  docKeywords: [
    "web SDK documentation",
    "browser session replay docs",
    "mobile SDK documentation",
    "React Native analytics documentation",
    "mobile session replay docs",
  ],
  engineeringMetaTitle: "Engineering Log - Technical articles | Rejourney",
  engineeringMetaDescription:
    "Technical articles on mobile session replay, map capture, GPU replay architecture, and lightweight mobile observability.",
  engineeringCollectionName: "Rejourney Engineering Log",
  engineeringFromTeam: "From the dev team",
  engineeringHeading: "Engineering",
  engineeringIntro:
    "Friendly technical notes from the Rejourney team on mobile replay, SDK architecture, map capture, infrastructure, and performance.",
  readArticleLabel: (title) => `Read ${title}`,
  articleMetaTitleSuffix: "Rejourney Engineering",
  articleDefaultDescription: (title, keyword) =>
    `${title}: a Rejourney engineering article about ${keyword}.`,
  backToEngineering: "Back to Engineering Log",
  authorHeading: "Author",
  engineeringTeamLabel: "Rejourney Engineering Team",
  viewLinkedIn: "View LinkedIn",
  viewGitHub: "View GitHub",
  readTime: (minutes) => `${minutes} min read`,
  pricing: {
    metaTitle: "Rejourney Pricing: Fixed-Price Mobile Analytics & Session Replay",
    metaDescription:
      "Rejourney pricing for mobile analytics, session replay, crash reporting, heatmaps, and self-hosted deployments.",
    metaKeywords: [
      "mobile analytics pricing",
      "mobile session replay pricing",
      "mobile app analytics pricing",
      "PostHog alternative pricing",
      "self-hosted analytics pricing",
      "mobile observability pricing",
    ],
    ogTitle: "Rejourney Pricing: Fixed-Price Mobile Analytics & Session Replay",
    ogDescription:
      "Simple fixed pricing for mobile session replay, heatmaps, crash reporting, journeys, and self-hosted analytics.",
    twitterTitle: "Rejourney Pricing: Fixed-Price Mobile Analytics",
    pageName: "Rejourney Pricing",
    ariaLabel: "Pricing",
    heading: "Pricing",
    intro:
      "Easy pricing based on session count. Every Session includes all core features.",
    contactEyebrow: "Contact devs",
    contactHeading: "Need a new feature?",
    copied: "Copied",
    contactEmail: "contact@rejourney.co",
    emailCopiedToast: "Email copied to clipboard.",
    planDescriptions: {
      free: "For early projects and production validation.",
      starter: "For apps starting to see regular traffic.",
      growth: "For growing teams with heavier replay volume.",
      pro: "For high-traffic apps and mature web and mobile teams.",
      fallback: "For mobile teams building with Rejourney.",
    },
    sharedFeatures: [
      "AI Replay Query Builder",
      "Crashes/ANRS/Errors",
      "Growth Analytics",
      "Geographic Analytics",
      "Journey Analytics",
      "Heat Maps",
      "Unlimited Analytics/Events",
      "Unlimited Data Retention (except replays)",
    ],
    popular: "Popular",
    perMonth: "per month",
    perYear: "per year",
    sessionsPerMonth: (sessions) => `${sessions} session replays`,
    replayRetention: (retention) => `${retention} replay retention`,
    startFree: "Start free",
    getStarted: "Get started",
    enterpriseEyebrow: "Enterprise",
    enterpriseHeading: (sessions) => `Need more than ${sessions} monthly sessions?`,
    enterpriseCopy:
      "Custom session volume, custom replay retention, and high performance storage buckets.",
    contact: "Contact",
    comparisonTitle: "Usage cost comparison",
    comparisonSubtitle: "Rejourney fixed pricing vs usage-based session replay pricing.",
    sessionsPerMonthLabel: "Sessions per month",
    monthlySessionsAriaLabel: "Monthly sessions",
    rejourneyPlanLabel: (plan, isCustom) => `${plan} plan${isCustom ? ", custom volume" : ""}`,
    posthogEstimate: "Usage-based replay estimate",
    sentryEstimate: "~$0.006 per replay add-on",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Run Rejourney on your own infrastructure.",
    selfHostedCopy: "Deploy with Docker or K3s and keep session data inside your environment.",
    viewSource: "View source",
  },
};

type ContentLocaleOverride = Partial<Omit<ContentLocaleCopy, "pricing">> & {
  pricing?: Partial<ContentLocaleCopy["pricing"]>;
};

const contentLocaleOverrides: Partial<Record<MarketingLocaleCode, ContentLocaleOverride>> = {
  ar: {
    docsIndexTitle: "توثيق Web وMobile SDK - Rejourney",
    docsIndexDescription:
      "توثيق Rejourney لتطبيقات الويب والجوال، بما في ذلك Browser SDK وsession replay وReact Native وSwift iOS وExpo والاستضافة الذاتية.",
    docsTitleSuffix: "توثيق Rejourney",
    docsSiteName: "توثيق Rejourney",
    docsBreadcrumb: "التوثيق",
    docsAiHeading: "استخدم AI للتكامل أسرع",
    docsCopyIntegrationPrompt: "نسخ prompt التكامل",
    docsCopied: "تم النسخ!",
    docsCopyCode: "نسخ",
    docsCopyCodeTitle: "نسخ الكود",
    docsCopyCommandTitle: "نسخ الأمر",
    docsNavGettingStarted: "بدء الاستخدام",
    docsNavInstallation: "التثبيت",
    docsNavBasicSetup: "الإعداد الأساسي",
    docsNavRouteTracking: "تتبع المسارات",
    docsNavUserIdentification: "تعريف المستخدم",
    docsNavCustomEvents: "الأحداث المخصصة",
    docsNavMetadata: "البيانات الوصفية",
    docsNavPrivacyControls: "عناصر التحكم بالخصوصية",
    documentationNotFoundTitle: "التوثيق غير موجود - Rejourney",
    documentationNotFoundHeading: "التوثيق غير موجود",
    documentationNotFoundCopy: "تعذر العثور على صفحة التوثيق المطلوبة.",
    docDefaultDescription: (title) => `توثيق ${title} لمنصة Rejourney مفتوحة المصدر لـ session replay وإعادة تشغيل الجلسات ومراقبة تطبيقات الجوال.`,
    docKeywords: ["session replay عربي", "session replay للجوال", "إعادة تشغيل الجلسات", "توثيق SDK للجوال", "توثيق React Native analytics", "توثيق mobile session replay"],
    engineeringMetaTitle: "سجل الهندسة - مقالات تقنية | Rejourney",
    engineeringMetaDescription:
      "مقالات تقنية حول session replay وإعادة تشغيل الجلسات للجوال، التقاط الخرائط، بنية GPU replay، والمراقبة الخفيفة للجوال.",
    engineeringCollectionName: "سجل هندسة Rejourney",
    engineeringFromTeam: "من فريق التطوير",
    engineeringHeading: "الهندسة",
    engineeringIntro: "ملاحظات تقنية من فريق Rejourney حول replay الجوال، بنية SDK، الخرائط، البنية التحتية، والأداء.",
    readArticleLabel: (title) => `اقرأ ${title}`,
    articleMetaTitleSuffix: "هندسة Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: مقال هندسي من Rejourney حول ${keyword}.`,
    backToEngineering: "العودة إلى سجل الهندسة",
    authorHeading: "الكاتب",
    engineeringTeamLabel: "فريق هندسة Rejourney",
    viewLinkedIn: "عرض LinkedIn",
    viewGitHub: "عرض GitHub",
    readTime: (minutes) => `${minutes} دقيقة قراءة`,
  },
  es: {
    docsIndexTitle: "Documentación del SDK web y móvil - Rejourney",
    docsIndexDescription:
      "Documentación de Rejourney para apps web y móviles, incluyendo Browser SDK, session replay, React Native, Swift iOS, Expo y self-hosting.",
    docsTitleSuffix: "Documentación de Rejourney",
    docsSiteName: "Documentación de Rejourney",
    docsBreadcrumb: "Docs",
    docsAiHeading: "Usa AI para integrar más rápido",
    docsCopyIntegrationPrompt: "Copiar prompt de integración",
    docsCopied: "Copiado",
    docsCopyCode: "Copiar",
    docsCopyCodeTitle: "Copiar código",
    docsCopyCommandTitle: "Copiar comando",
    docsNavGettingStarted: "Primeros pasos",
    docsNavInstallation: "Instalación",
    docsNavBasicSetup: "Configuración básica",
    docsNavRouteTracking: "Seguimiento de rutas",
    docsNavUserIdentification: "Identificación de usuarios",
    docsNavCustomEvents: "Eventos personalizados",
    docsNavMetadata: "Metadatos",
    docsNavPrivacyControls: "Controles de privacidad",
    documentationNotFoundTitle: "Documentación no encontrada - Rejourney",
    documentationNotFoundHeading: "Documentación no encontrada",
    documentationNotFoundCopy: "No se pudo encontrar la página de documentación solicitada.",
    docDefaultDescription: (title) => `Documentación de ${title} para la plataforma open source de session replay, reproducción de sesiones y observabilidad móvil de Rejourney.`,
    docKeywords: ["session replay español", "session replay móvil", "reproducción de sesiones", "replay de sesiones móviles", "documentación SDK móvil", "documentación analytics React Native", "documentación session replay móvil"],
    engineeringMetaTitle: "Engineering Log - Artículos técnicos | Rejourney",
    engineeringMetaDescription:
      "Artículos técnicos sobre session replay y reproducción de sesiones móvil, captura de mapas, arquitectura GPU replay y observabilidad móvil ligera.",
    engineeringCollectionName: "Rejourney Engineering Log",
    engineeringFromTeam: "Del equipo dev",
    engineeringHeading: "Ingeniería",
    engineeringIntro:
      "Notas técnicas del equipo de Rejourney sobre replay móvil, arquitectura SDK, captura de mapas, infraestructura y rendimiento.",
    readArticleLabel: (title) => `Leer ${title}`,
    articleMetaTitleSuffix: "Ingeniería Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: un artículo de ingeniería de Rejourney sobre ${keyword}.`,
    backToEngineering: "Volver al Engineering Log",
    authorHeading: "Autor",
    engineeringTeamLabel: "Equipo de ingeniería de Rejourney",
    viewLinkedIn: "Ver LinkedIn",
    viewGitHub: "Ver GitHub",
    readTime: (minutes) => `${minutes} min de lectura`,
  },
  tr: {
    docsIndexTitle: "Web ve Mobil SDK Dokümantasyonu - Rejourney",
    docsIndexDescription:
      "Browser SDK, web ve mobil session replay, React Native, Swift iOS, Expo, self-hosting ve mimari kılavuzları için Rejourney dokümantasyonu.",
    docsTitleSuffix: "Rejourney Dokümantasyonu",
    docsSiteName: "Rejourney Dokümantasyonu",
    docsBreadcrumb: "Dokümanlar",
    docsAiHeading: "Daha hızlı entegre etmek için AI kullan",
    docsCopyIntegrationPrompt: "Entegrasyon promptunu kopyala",
    docsCopied: "Kopyalandı!",
    docsCopyCode: "Kopyala",
    docsCopyCodeTitle: "Kodu kopyala",
    docsCopyCommandTitle: "Komutu kopyala",
    docsNavGettingStarted: "Başlangıç",
    docsNavInstallation: "Kurulum",
    docsNavBasicSetup: "Temel kurulum",
    docsNavRouteTracking: "Route tracking",
    docsNavUserIdentification: "Kullanıcı kimliği",
    docsNavCustomEvents: "Custom events",
    docsNavMetadata: "Metadata",
    docsNavPrivacyControls: "Gizlilik kontrolleri",
    documentationNotFoundTitle: "Dokümantasyon Bulunamadı - Rejourney",
    documentationNotFoundHeading: "Dokümantasyon Bulunamadı",
    documentationNotFoundCopy: "İstenen dokümantasyon sayfası bulunamadı.",
    docDefaultDescription: (title) => `Rejourney'in açık kaynak mobil session replay, oturum tekrarı ve gözlemlenebilirlik platformu için ${title} dokümantasyonu.`,
    docKeywords: ["session replay türkçe", "mobil session replay", "oturum tekrarı", "mobil oturum yeniden oynatma", "mobil SDK dokümantasyonu", "React Native analytics dokümantasyonu", "mobil session replay dokümantasyonu"],
    engineeringMetaTitle: "Engineering Log - Teknik yazılar | Rejourney",
    engineeringMetaDescription:
      "Mobil session replay, oturum tekrarı, harita yakalama, GPU replay mimarisi ve hafif mobil gözlemlenebilirlik üzerine teknik yazılar.",
    engineeringCollectionName: "Rejourney Engineering Log",
    engineeringFromTeam: "Geliştirici ekibinden",
    engineeringHeading: "Mühendislik",
    engineeringIntro:
      "Rejourney ekibinden mobil replay, SDK mimarisi, harita yakalama, altyapı ve performans üzerine teknik notlar.",
    readArticleLabel: (title) => `${title} yazısını oku`,
    articleMetaTitleSuffix: "Rejourney Mühendislik",
    articleDefaultDescription: (title, keyword) => `${title}: ${keyword} hakkında bir Rejourney mühendislik yazısı.`,
    backToEngineering: "Engineering Log'a dön",
    authorHeading: "Yazar",
    engineeringTeamLabel: "Rejourney Mühendislik Ekibi",
    viewLinkedIn: "LinkedIn'i görüntüle",
    viewGitHub: "GitHub'ı görüntüle",
    readTime: (minutes) => `${minutes} dk okuma`,
  },
  fr: {
    docsIndexTitle: "Documentation SDK web et mobile - Rejourney",
    docsIndexDescription:
      "Documentation Rejourney pour apps web et mobiles, avec Browser SDK, React Native, Swift iOS, Expo, auto-hébergement et guides d'architecture.",
    docsTitleSuffix: "Documentation Rejourney",
    docsSiteName: "Documentation Rejourney",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Documentation introuvable - Rejourney",
    documentationNotFoundHeading: "Documentation introuvable",
    documentationNotFoundCopy: "La page de documentation demandée est introuvable.",
    docDefaultDescription: (title) => `Documentation ${title} pour la plateforme open source d'observabilité mobile de Rejourney.`,
    engineeringMetaTitle: "Engineering Log - Articles techniques | Rejourney",
    engineeringMetaDescription:
      "Articles techniques sur le session replay mobile, la capture de cartes, l'architecture GPU replay et l'observabilité mobile légère.",
    engineeringFromTeam: "Par l'équipe dev",
    engineeringHeading: "Ingénierie",
    engineeringIntro:
      "Notes techniques de l'équipe Rejourney sur le replay mobile, l'architecture SDK, la capture de cartes, l'infrastructure et la performance.",
    readArticleLabel: (title) => `Lire ${title}`,
    articleMetaTitleSuffix: "Ingénierie Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: un article d'ingénierie Rejourney sur ${keyword}.`,
    backToEngineering: "Retour à l'Engineering Log",
    authorHeading: "Auteur",
    engineeringTeamLabel: "Équipe ingénierie Rejourney",
    viewLinkedIn: "Voir LinkedIn",
    viewGitHub: "Voir GitHub",
    readTime: (minutes) => `${minutes} min de lecture`,
  },
  de: {
    docsIndexTitle: "Web- und Mobile-SDK Dokumentation - Rejourney",
    docsIndexDescription:
      "Rejourney Dokumentation für Web- und Mobile-Apps, inklusive Browser SDK, React Native, Swift iOS, Expo, Self-Hosting und Architektur-Guides.",
    docsTitleSuffix: "Rejourney Dokumentation",
    docsSiteName: "Rejourney Dokumentation",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Dokumentation nicht gefunden - Rejourney",
    documentationNotFoundHeading: "Dokumentation nicht gefunden",
    documentationNotFoundCopy: "Die angeforderte Dokumentationsseite wurde nicht gefunden.",
    docDefaultDescription: (title) => `${title} Dokumentation für Rejourneys Open-Source-Plattform für Mobile Observability.`,
    engineeringMetaTitle: "Engineering Log - Technische Artikel | Rejourney",
    engineeringMetaDescription:
      "Technische Artikel über Mobile Session Replay, Map Capture, GPU-Replay-Architektur und leichtgewichtige Mobile Observability.",
    engineeringFromTeam: "Aus dem Dev-Team",
    engineeringHeading: "Engineering",
    engineeringIntro:
      "Technische Notizen des Rejourney-Teams zu Mobile Replay, SDK-Architektur, Map Capture, Infrastruktur und Performance.",
    readArticleLabel: (title) => `${title} lesen`,
    articleMetaTitleSuffix: "Rejourney Engineering",
    articleDefaultDescription: (title, keyword) => `${title}: ein Rejourney Engineering-Artikel über ${keyword}.`,
    backToEngineering: "Zurück zum Engineering Log",
    authorHeading: "Autor",
    engineeringTeamLabel: "Rejourney Engineering Team",
    viewLinkedIn: "LinkedIn ansehen",
    viewGitHub: "GitHub ansehen",
    readTime: (minutes) => `${minutes} Min. Lesezeit`,
  },
  it: {
    docsIndexTitle: "Documentazione SDK web e mobile - Rejourney",
    docsIndexDescription:
      "Documentazione Rejourney per app web e mobile, inclusi Browser SDK, React Native, Swift iOS, Expo, self-hosting e guide di architettura.",
    docsTitleSuffix: "Documentazione Rejourney",
    docsSiteName: "Documentazione Rejourney",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Documentazione non trovata - Rejourney",
    documentationNotFoundHeading: "Documentazione non trovata",
    documentationNotFoundCopy: "La pagina di documentazione richiesta non è stata trovata.",
    docDefaultDescription: (title) => `Documentazione ${title} per la piattaforma open source di osservabilità mobile di Rejourney.`,
    engineeringMetaTitle: "Engineering Log - Articoli tecnici | Rejourney",
    engineeringMetaDescription:
      "Articoli tecnici su session replay mobile, map capture, architettura GPU replay e osservabilità mobile leggera.",
    engineeringFromTeam: "Dal team dev",
    engineeringHeading: "Ingegneria",
    engineeringIntro:
      "Note tecniche del team Rejourney su mobile replay, architettura SDK, map capture, infrastruttura e performance.",
    readArticleLabel: (title) => `Leggi ${title}`,
    articleMetaTitleSuffix: "Ingegneria Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: un articolo di ingegneria Rejourney su ${keyword}.`,
    backToEngineering: "Torna all'Engineering Log",
    authorHeading: "Autore",
    engineeringTeamLabel: "Team ingegneria Rejourney",
    viewLinkedIn: "Vedi LinkedIn",
    viewGitHub: "Vedi GitHub",
    readTime: (minutes) => `${minutes} min di lettura`,
  },
  nl: {
    docsIndexTitle: "Web- en mobiele SDK documentatie - Rejourney",
    docsIndexDescription:
      "Rejourney documentatie voor web- en mobiele apps, inclusief Browser SDK, React Native, Swift iOS, Expo, self-hosting en architectuurgidsen.",
    docsTitleSuffix: "Rejourney Documentatie",
    docsSiteName: "Rejourney Documentatie",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Documentatie niet gevonden - Rejourney",
    documentationNotFoundHeading: "Documentatie niet gevonden",
    documentationNotFoundCopy: "De gevraagde documentatiepagina kon niet worden gevonden.",
    docDefaultDescription: (title) => `${title} documentatie voor Rejourney's open-source platform voor mobiele observability.`,
    engineeringMetaTitle: "Engineering Log - Technische artikelen | Rejourney",
    engineeringMetaDescription:
      "Technische artikelen over mobiele session replay, map capture, GPU replay architectuur en lichte mobiele observability.",
    engineeringFromTeam: "Van het dev-team",
    engineeringHeading: "Engineering",
    engineeringIntro:
      "Technische notities van het Rejourney-team over mobiele replay, SDK-architectuur, map capture, infrastructuur en performance.",
    readArticleLabel: (title) => `Lees ${title}`,
    articleMetaTitleSuffix: "Rejourney Engineering",
    articleDefaultDescription: (title, keyword) => `${title}: een Rejourney engineering-artikel over ${keyword}.`,
    backToEngineering: "Terug naar Engineering Log",
    authorHeading: "Auteur",
    engineeringTeamLabel: "Rejourney Engineering Team",
    viewLinkedIn: "LinkedIn bekijken",
    viewGitHub: "GitHub bekijken",
    readTime: (minutes) => `${minutes} min leestijd`,
  },
  pl: {
    docsIndexTitle: "Dokumentacja SDK web i mobile - Rejourney",
    docsIndexDescription:
      "Dokumentacja Rejourney dla aplikacji web i mobile, w tym Browser SDK, React Native, Swift iOS, Expo, self-hosting i przewodniki architektury.",
    docsTitleSuffix: "Dokumentacja Rejourney",
    docsSiteName: "Dokumentacja Rejourney",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Nie znaleziono dokumentacji - Rejourney",
    documentationNotFoundHeading: "Nie znaleziono dokumentacji",
    documentationNotFoundCopy: "Nie znaleziono żądanej strony dokumentacji.",
    docDefaultDescription: (title) => `Dokumentacja ${title} dla open-source platformy Rejourney do obserwowalności mobilnej.`,
    engineeringMetaTitle: "Engineering Log - Artykuły techniczne | Rejourney",
    engineeringMetaDescription:
      "Artykuły techniczne o mobile session replay, map capture, architekturze GPU replay i lekkiej obserwowalności mobilnej.",
    engineeringFromTeam: "Od zespołu dev",
    engineeringHeading: "Inżynieria",
    engineeringIntro:
      "Notatki techniczne zespołu Rejourney o mobile replay, architekturze SDK, map capture, infrastrukturze i wydajności.",
    readArticleLabel: (title) => `Przeczytaj ${title}`,
    articleMetaTitleSuffix: "Inżynieria Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: artykuł inżynieryjny Rejourney o ${keyword}.`,
    backToEngineering: "Wróć do Engineering Log",
    authorHeading: "Autor",
    engineeringTeamLabel: "Zespół inżynierii Rejourney",
    viewLinkedIn: "Zobacz LinkedIn",
    viewGitHub: "Zobacz GitHub",
    readTime: (minutes) => `${minutes} min czytania`,
  },
  pt: {
    docsIndexTitle: "Documentação do SDK web e mobile - Rejourney",
    docsIndexDescription:
      "Documentação Rejourney para apps web e mobile, incluindo Browser SDK, React Native, Swift iOS, Expo, self-hosting e guias de arquitetura.",
    docsTitleSuffix: "Documentação Rejourney",
    docsSiteName: "Documentação Rejourney",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Documentação não encontrada - Rejourney",
    documentationNotFoundHeading: "Documentação não encontrada",
    documentationNotFoundCopy: "A página de documentação pedida não foi encontrada.",
    docDefaultDescription: (title) => `Documentação ${title} para a plataforma open source de observabilidade mobile da Rejourney.`,
    engineeringMetaTitle: "Engineering Log - Artigos técnicos | Rejourney",
    engineeringMetaDescription:
      "Artigos técnicos sobre session replay mobile, captura de mapas, arquitetura GPU replay e observabilidade mobile leve.",
    engineeringFromTeam: "Da equipa dev",
    engineeringHeading: "Engenharia",
    engineeringIntro:
      "Notas técnicas da equipa Rejourney sobre mobile replay, arquitetura SDK, captura de mapas, infraestrutura e desempenho.",
    readArticleLabel: (title) => `Ler ${title}`,
    articleMetaTitleSuffix: "Engenharia Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: um artigo de engenharia Rejourney sobre ${keyword}.`,
    backToEngineering: "Voltar ao Engineering Log",
    authorHeading: "Autor",
    engineeringTeamLabel: "Equipa de engenharia Rejourney",
    viewLinkedIn: "Ver LinkedIn",
    viewGitHub: "Ver GitHub",
    readTime: (minutes) => `${minutes} min de leitura`,
  },
  "pt-br": {
    docsIndexTitle: "Documentação do SDK web e mobile - Rejourney",
    docsIndexDescription:
      "Documentação Rejourney para apps web e mobile, incluindo Browser SDK, React Native, Swift iOS, Expo, self-hosting e guias de arquitetura.",
    docsTitleSuffix: "Documentação Rejourney",
    docsSiteName: "Documentação Rejourney",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Documentação não encontrada - Rejourney",
    documentationNotFoundHeading: "Documentação não encontrada",
    documentationNotFoundCopy: "A página de documentação solicitada não foi encontrada.",
    docDefaultDescription: (title) => `Documentação ${title} para a plataforma open source de observabilidade mobile da Rejourney.`,
    engineeringMetaTitle: "Engineering Log - Artigos técnicos | Rejourney",
    engineeringMetaDescription:
      "Artigos técnicos sobre session replay mobile, captura de mapas, arquitetura GPU replay e observabilidade mobile leve.",
    engineeringFromTeam: "Do time dev",
    engineeringHeading: "Engenharia",
    engineeringIntro:
      "Notas técnicas do time Rejourney sobre mobile replay, arquitetura SDK, captura de mapas, infraestrutura e performance.",
    readArticleLabel: (title) => `Ler ${title}`,
    articleMetaTitleSuffix: "Engenharia Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: um artigo de engenharia Rejourney sobre ${keyword}.`,
    backToEngineering: "Voltar ao Engineering Log",
    authorHeading: "Autor",
    engineeringTeamLabel: "Time de engenharia Rejourney",
    viewLinkedIn: "Ver LinkedIn",
    viewGitHub: "Ver GitHub",
    readTime: (minutes) => `${minutes} min de leitura`,
  },
  ru: {
    docsIndexTitle: "Документация Web и Mobile SDK - Rejourney",
    docsIndexDescription:
      "Документация Rejourney для web и mobile приложений: Browser SDK, React Native, Swift iOS, Expo, self-hosting и архитектурные руководства.",
    docsTitleSuffix: "Документация Rejourney",
    docsSiteName: "Документация Rejourney",
    docsBreadcrumb: "Документация",
    documentationNotFoundTitle: "Документация не найдена - Rejourney",
    documentationNotFoundHeading: "Документация не найдена",
    documentationNotFoundCopy: "Запрошенная страница документации не найдена.",
    docDefaultDescription: (title) => `Документация ${title} для open-source платформы мобильной observability Rejourney.`,
    engineeringMetaTitle: "Engineering Log - Технические статьи | Rejourney",
    engineeringMetaDescription:
      "Технические статьи о mobile session replay, map capture, GPU replay architecture и легкой mobile observability.",
    engineeringFromTeam: "От dev-команды",
    engineeringHeading: "Инженерия",
    engineeringIntro:
      "Технические заметки команды Rejourney о mobile replay, SDK architecture, map capture, инфраструктуре и performance.",
    readArticleLabel: (title) => `Читать ${title}`,
    articleMetaTitleSuffix: "Инженерия Rejourney",
    articleDefaultDescription: (title, keyword) => `${title}: инженерная статья Rejourney о ${keyword}.`,
    backToEngineering: "Назад к Engineering Log",
    authorHeading: "Автор",
    engineeringTeamLabel: "Инженерная команда Rejourney",
    viewLinkedIn: "Открыть LinkedIn",
    viewGitHub: "Открыть GitHub",
    readTime: (minutes) => `${minutes} мин чтения`,
  },
  vi: {
    docsIndexTitle: "Tài liệu Web và Mobile SDK - Rejourney",
    docsIndexDescription:
      "Tài liệu Rejourney cho app web và mobile, gồm Browser SDK, React Native, Swift iOS, Expo, self-hosting và hướng dẫn kiến trúc.",
    docsTitleSuffix: "Tài liệu Rejourney",
    docsSiteName: "Tài liệu Rejourney",
    docsBreadcrumb: "Docs",
    documentationNotFoundTitle: "Không tìm thấy tài liệu - Rejourney",
    documentationNotFoundHeading: "Không tìm thấy tài liệu",
    documentationNotFoundCopy: "Không tìm thấy trang tài liệu được yêu cầu.",
    docDefaultDescription: (title) => `Tài liệu ${title} cho nền tảng mobile observability open source của Rejourney.`,
    engineeringMetaTitle: "Engineering Log - Bài viết kỹ thuật | Rejourney",
    engineeringMetaDescription:
      "Bài viết kỹ thuật về mobile session replay, map capture, kiến trúc GPU replay và mobile observability nhẹ.",
    engineeringFromTeam: "Từ đội dev",
    engineeringHeading: "Engineering",
    engineeringIntro:
      "Ghi chú kỹ thuật từ đội Rejourney về mobile replay, kiến trúc SDK, map capture, hạ tầng và performance.",
    readArticleLabel: (title) => `Đọc ${title}`,
    articleMetaTitleSuffix: "Rejourney Engineering",
    articleDefaultDescription: (title, keyword) => `${title}: bài viết engineering của Rejourney về ${keyword}.`,
    backToEngineering: "Quay lại Engineering Log",
    authorHeading: "Tác giả",
    engineeringTeamLabel: "Đội engineering Rejourney",
    viewLinkedIn: "Xem LinkedIn",
    viewGitHub: "Xem GitHub",
    readTime: (minutes) => `${minutes} phút đọc`,
  },
};

const pricingLocaleOverrides: Partial<Record<MarketingLocaleCode, Partial<ContentLocaleCopy["pricing"]>>> = {
  ar: {
    metaTitle: "أسعار Rejourney: Session Replay وإعادة تشغيل الجلسات بسعر ثابت",
    metaDescription: "أسعار Rejourney لتحليلات الجوال، session replay، إعادة تشغيل الجلسات، تقارير الأعطال، الخرائط الحرارية، والاستضافة الذاتية.",
    metaKeywords: [
      "session replay عربي",
      "أسعار session replay",
      "إعادة تشغيل الجلسات",
      "تحليلات تطبيقات الجوال",
      "تحليلات React Native",
      "خرائط حرارية للجوال",
      "استضافة ذاتية للتحليلات",
    ],
    ogTitle: "أسعار Rejourney: Session Replay وإعادة تشغيل الجلسات بسعر ثابت",
    ogDescription: "أسعار ثابتة وبسيطة لـ session replay وإعادة تشغيل الجلسات للجوال، الخرائط الحرارية، الأعطال، الرحلات، والتحليلات الذاتية الاستضافة.",
    twitterTitle: "أسعار Rejourney: تحليلات جوال بسعر ثابت",
    pageName: "أسعار Rejourney",
    ariaLabel: "الأسعار",
    heading: "الأسعار",
    intro: "خطط شهرية ثابتة لـ session replay وإعادة تشغيل الجلسات وتحليلات الجوال. اختر حسب حجم الجلسات؛ والميزات الأساسية تبقى مشمولة.",
    contactEyebrow: "تواصل مع المطورين",
    contactHeading: "تحتاج ميزة جديدة؟",
    copied: "تم النسخ",
    emailCopiedToast: "تم نسخ البريد الإلكتروني.",
    planDescriptions: {
      free: "للمشاريع المبكرة والتحقق في الإنتاج.",
      starter: "للتطبيقات التي بدأت ترى زيارات منتظمة.",
      growth: "للفرق النامية ذات حجم replay أكبر.",
      pro: "للتطبيقات عالية الزيارات وفرق الجوال الناضجة.",
      fallback: "لفرق الجوال التي تبني مع Rejourney.",
    },
    sharedFeatures: [
      "AI Replay Query Builder",
      "الأعطال وANR والأخطاء",
      "تحليلات النمو",
      "تحليلات جغرافية",
      "تحليلات الرحلات",
      "خرائط حرارية",
      "تحليلات وأحداث غير محدودة",
      "احتفاظ غير محدود بالبيانات باستثناء replays",
    ],
    popular: "الأكثر شيوعًا",
    perMonth: "شهريًا",
    perYear: "سنويًا",
    sessionsPerMonth: (sessions) => `${sessions} إعادة تشغيل جلسات مجانية`,
    replayRetention: (retention) => `احتفاظ replay لمدة ${retention}`,
    startFree: "ابدأ مجانًا",
    getStarted: "ابدأ الآن",
    enterpriseEyebrow: "المؤسسات",
    enterpriseHeading: (sessions) => `تحتاج أكثر من ${sessions} جلسة شهرية؟`,
    enterpriseCopy: "حجم جلسات مخصص، احتفاظ replay مخصص، وحاويات تخزين عالية الأداء.",
    contact: "تواصل",
    comparisonTitle: "مقارنة تكلفة الاستخدام",
    comparisonSubtitle: "تسعير Rejourney الثابت مقابل تسعير session replay حسب الاستخدام.",
    sessionsPerMonthLabel: "الجلسات شهريًا",
    monthlySessionsAriaLabel: "الجلسات الشهرية",
    rejourneyPlanLabel: (plan, isCustom) => `خطة ${plan}${isCustom ? "، حجم مخصص" : ""}`,
    posthogEstimate: "تقدير replay حسب الاستخدام",
    sentryEstimate: "~$0.006 لكل إضافة replay",
    selfHostedEyebrow: "استضافة ذاتية",
    selfHostedHeading: "شغّل Rejourney على بنيتك التحتية.",
    selfHostedCopy: "انشر باستخدام Docker أو K3s واحتفظ ببيانات الجلسات داخل بيئتك.",
    viewSource: "عرض المصدر",
  },
  es: {
    metaTitle: "Precios de Rejourney: session replay y reproducción de sesiones",
    metaDescription: "Precios de Rejourney para analítica móvil, session replay, reproducción de sesiones, crashes, heatmaps y despliegues self-hosted.",
    metaKeywords: [
      "session replay español",
      "precios session replay",
      "session replay móvil",
      "reproducción de sesiones",
      "analítica móvil",
      "analítica React Native",
      "heatmaps móviles",
      "analítica self-hosted",
    ],
    ogTitle: "Precios de Rejourney: session replay y reproducción de sesiones",
    ogDescription: "Precios simples y fijos para session replay y reproducción de sesiones móvil, heatmaps, crashes, journeys y analítica self-hosted.",
    twitterTitle: "Precios de Rejourney: analítica móvil a precio fijo",
    pageName: "Precios de Rejourney",
    ariaLabel: "Precios",
    heading: "Precios",
    intro: "Planes mensuales fijos para session replay, reproducción de sesiones y analítica móvil. Elige por volumen de sesiones; las funciones clave siguen incluidas.",
    contactEyebrow: "Contacta al equipo dev",
    contactHeading: "¿Necesitas una función nueva?",
    copied: "Copiado",
    emailCopiedToast: "Correo copiado al portapapeles.",
    planDescriptions: {
      free: "Para proyectos iniciales y validación en producción.",
      starter: "Para apps que empiezan a tener tráfico regular.",
      growth: "Para equipos en crecimiento con más volumen de replay.",
      pro: "Para apps de alto tráfico y equipos móviles maduros.",
      fallback: "Para equipos móviles que construyen con Rejourney.",
    },
    sharedFeatures: [
      "AI Replay Query Builder",
      "Crashes/ANR/errores",
      "Analítica de crecimiento",
      "Analítica geográfica",
      "Analítica de journeys",
      "Heatmaps",
      "Analítica/eventos ilimitados",
      "Retención de datos ilimitada excepto replays",
    ],
    popular: "Popular",
    perMonth: "al mes",
    perYear: "al año",
    sessionsPerMonth: (sessions) => `${sessions} session replays gratis`,
    replayRetention: (retention) => `${retention} de retención de replay`,
    startFree: "Empieza gratis",
    getStarted: "Empezar",
    enterpriseEyebrow: "Enterprise",
    enterpriseHeading: (sessions) => `¿Necesitas más de ${sessions} sesiones mensuales?`,
    enterpriseCopy: "Volumen de sesiones personalizado, retención de replay personalizada y buckets de almacenamiento de alto rendimiento.",
    contact: "Contacto",
    comparisonTitle: "Comparación de coste de uso",
    comparisonSubtitle: "Precio fijo de Rejourney frente a session replay basado en uso.",
    sessionsPerMonthLabel: "Sesiones al mes",
    monthlySessionsAriaLabel: "Sesiones mensuales",
    rejourneyPlanLabel: (plan, isCustom) => `Plan ${plan}${isCustom ? ", volumen personalizado" : ""}`,
    posthogEstimate: "Estimación de replay basada en uso",
    sentryEstimate: "~$0.006 por add-on de replay",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Ejecuta Rejourney en tu propia infraestructura.",
    selfHostedCopy: "Despliega con Docker o K3s y mantén los datos de sesiones dentro de tu entorno.",
    viewSource: "Ver código fuente",
  },
  tr: {
    metaTitle: "Rejourney Fiyatları: Mobil session replay ve oturum tekrarı",
    metaDescription: "Mobil analitik, session replay, oturum tekrarı, crash raporlama, heatmap ve self-hosted dağıtımlar için Rejourney fiyatları.",
    metaKeywords: [
      "session replay türkçe",
      "session replay fiyatları",
      "mobil session replay",
      "oturum tekrarı",
      "mobil analitik",
      "React Native analitik",
      "mobil heatmap",
      "self-hosted analitik",
    ],
    ogTitle: "Rejourney Fiyatları: Mobil session replay ve oturum tekrarı",
    ogDescription: "Mobil session replay, oturum tekrarı, heatmap, crash raporlama, journey ve self-hosted analitik için sade sabit fiyatlandırma.",
    twitterTitle: "Rejourney Fiyatları: Sabit fiyatlı mobil analitik",
    pageName: "Rejourney Fiyatları",
    ariaLabel: "Fiyatlar",
    heading: "Fiyatlar",
    intro: "Mobil session replay, oturum tekrarı ve analitik için sabit aylık planlar. Oturum hacmine göre seç; temel özellikler dahil kalır.",
    contactEyebrow: "Geliştiricilerle iletişim",
    contactHeading: "Yeni bir özelliğe mi ihtiyacın var?",
    copied: "Kopyalandı",
    emailCopiedToast: "E-posta panoya kopyalandı.",
    planDescriptions: {
      free: "Erken projeler ve production doğrulaması için.",
      starter: "Düzenli trafik görmeye başlayan uygulamalar için.",
      growth: "Daha yoğun replay hacmine sahip büyüyen ekipler için.",
      pro: "Yüksek trafikli uygulamalar ve olgun mobil ekipler için.",
      fallback: "Rejourney ile geliştiren mobil ekipler için.",
    },
    sharedFeatures: [
      "AI Replay Query Builder",
      "Crash/ANR/hatalar",
      "Büyüme analitiği",
      "Coğrafi analitik",
      "Journey analitiği",
      "Heatmapler",
      "Sınırsız analitik/event",
      "Replay hariç sınırsız veri saklama",
    ],
    popular: "Popüler",
    perMonth: "aylık",
    perYear: "yıllık",
    sessionsPerMonth: (sessions) => `${sessions} ücretsiz session replay`,
    replayRetention: (retention) => `${retention} replay saklama`,
    startFree: "Ücretsiz başla",
    getStarted: "Başla",
    enterpriseEyebrow: "Enterprise",
    enterpriseHeading: (sessions) => `Ayda ${sessions} üzeri oturum mu gerekiyor?`,
    enterpriseCopy: "Özel oturum hacmi, özel replay saklama ve yüksek performanslı storage bucket'ları.",
    contact: "İletişim",
    comparisonTitle: "Kullanım maliyeti karşılaştırması",
    comparisonSubtitle: "Rejourney sabit fiyatlandırma ve kullanıma dayalı session replay fiyatları.",
    sessionsPerMonthLabel: "Aylık oturum",
    monthlySessionsAriaLabel: "Aylık oturumlar",
    rejourneyPlanLabel: (plan, isCustom) => `${plan} planı${isCustom ? ", özel hacim" : ""}`,
    posthogEstimate: "Kullanıma dayalı replay tahmini",
    sentryEstimate: "~Replay add-on başına $0.006",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Rejourney'i kendi altyapında çalıştır.",
    selfHostedCopy: "Docker veya K3s ile dağıt ve oturum verilerini kendi ortamında tut.",
    viewSource: "Kaynağı görüntüle",
  },
  fr: {
    metaTitle: "Tarifs Rejourney: analytics mobile et session replay à prix fixe",
    metaDescription: "Tarifs Rejourney pour analytics mobile, session replay, crashs, heatmaps et déploiements self-hosted.",
    ogTitle: "Tarifs Rejourney: analytics mobile et session replay à prix fixe",
    ogDescription: "Tarifs fixes pour session replay mobile, heatmaps, crashs, parcours et analytics self-hosted.",
    twitterTitle: "Tarifs Rejourney: analytics mobile à prix fixe",
    pageName: "Tarifs Rejourney",
    ariaLabel: "Tarifs",
    heading: "Tarifs",
    intro: "Plans mensuels fixes pour le session replay et l'analytics mobile. Choisissez par volume de sessions; les fonctionnalités clés restent incluses.",
    contactEyebrow: "Contacter les devs",
    contactHeading: "Besoin d'une nouvelle fonctionnalité?",
    copied: "Copié",
    emailCopiedToast: "Email copié dans le presse-papiers.",
    perMonth: "par mois",
    perYear: "par an",
    sessionsPerMonth: (sessions) => `${sessions} replays de session gratuits`,
    replayRetention: (retention) => `${retention} de rétention replay`,
    startFree: "Démarrer gratuitement",
    getStarted: "Démarrer",
    contact: "Contact",
    comparisonTitle: "Comparaison des coûts",
    sessionsPerMonthLabel: "Sessions par mois",
    monthlySessionsAriaLabel: "Sessions mensuelles",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Exécutez Rejourney sur votre propre infrastructure.",
    viewSource: "Voir le code source",
  },
  de: {
    metaTitle: "Rejourney Preise: Mobile Analytics und Session Replay zum Festpreis",
    metaDescription: "Rejourney Preise für Mobile Analytics, Session Replay, Crash Reporting, Heatmaps und Self-Hosted Deployments.",
    ogTitle: "Rejourney Preise: Mobile Analytics und Session Replay zum Festpreis",
    ogDescription: "Einfache Festpreise für Mobile Session Replay, Heatmaps, Crash Reporting, Journeys und Self-Hosted Analytics.",
    twitterTitle: "Rejourney Preise: Mobile Analytics zum Festpreis",
    pageName: "Rejourney Preise",
    ariaLabel: "Preise",
    heading: "Preise",
    intro: "Feste monatliche Pläne für Mobile Session Replay und Analytics. Wählen Sie nach Sitzungsvolumen; die Kernfunktionen bleiben enthalten.",
    contactEyebrow: "Devs kontaktieren",
    contactHeading: "Brauchen Sie ein neues Feature?",
    copied: "Kopiert",
    emailCopiedToast: "E-Mail wurde kopiert.",
    perMonth: "pro Monat",
    perYear: "pro Jahr",
    sessionsPerMonth: (sessions) => `${sessions} kostenlose Session Replays`,
    replayRetention: (retention) => `${retention} Replay-Aufbewahrung`,
    startFree: "Kostenlos starten",
    getStarted: "Loslegen",
    contact: "Kontakt",
    comparisonTitle: "Kostenvergleich",
    sessionsPerMonthLabel: "Sessions pro Monat",
    monthlySessionsAriaLabel: "Monatliche Sessions",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Betreiben Sie Rejourney auf Ihrer eigenen Infrastruktur.",
    viewSource: "Quellcode ansehen",
  },
  "pt-br": {
    metaTitle: "Preços Rejourney: analytics mobile e session replay com preço fixo",
    metaDescription: "Preços Rejourney para analytics mobile, session replay, crash reporting, mapas de calor e self-hosted.",
    ogTitle: "Preços Rejourney: analytics mobile e session replay com preço fixo",
    ogDescription: "Preços fixos para session replay mobile, mapas de calor, crashes, jornadas e analytics self-hosted.",
    twitterTitle: "Preços Rejourney: analytics mobile com preço fixo",
    pageName: "Preços Rejourney",
    ariaLabel: "Preços",
    heading: "Preços",
    intro: "Planos mensais fixos para session replay e analytics mobile. Escolha por volume de sessões; os recursos principais continuam incluídos.",
    contactEyebrow: "Fale com devs",
    contactHeading: "Precisa de um novo recurso?",
    copied: "Copiado",
    emailCopiedToast: "Email copiado.",
    perMonth: "por mês",
    perYear: "por ano",
    sessionsPerMonth: (sessions) => `${sessions} replays de sessão grátis`,
    replayRetention: (retention) => `${retention} de retenção de replay`,
    startFree: "Comece grátis",
    getStarted: "Começar",
    contact: "Contato",
    comparisonTitle: "Comparação de custo de uso",
    sessionsPerMonthLabel: "Sessões por mês",
    monthlySessionsAriaLabel: "Sessões mensais",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Rode o Rejourney na sua própria infraestrutura.",
    viewSource: "Ver código-fonte",
  },
  pt: {
    metaTitle: "Preços Rejourney: analytics mobile e session replay com preço fixo",
    metaDescription: "Preços Rejourney para analytics mobile, session replay, crash reporting, mapas de calor e self-hosted.",
    ogTitle: "Preços Rejourney: analytics mobile e session replay com preço fixo",
    ogDescription: "Preços fixos para session replay mobile, mapas de calor, crashes, jornadas e analytics self-hosted.",
    twitterTitle: "Preços Rejourney: analytics mobile com preço fixo",
    pageName: "Preços Rejourney",
    ariaLabel: "Preços",
    heading: "Preços",
    intro: "Planos mensais fixos para session replay e analytics mobile. Escolha por volume de sessões; as funcionalidades principais ficam incluídas.",
    contactEyebrow: "Contactar devs",
    contactHeading: "Precisa de uma nova funcionalidade?",
    copied: "Copiado",
    emailCopiedToast: "Email copiado.",
    perMonth: "por mês",
    perYear: "por ano",
    sessionsPerMonth: (sessions) => `${sessions} replays de sessão grátis`,
    replayRetention: (retention) => `${retention} de retenção de replay`,
    startFree: "Comece grátis",
    getStarted: "Começar",
    contact: "Contacto",
    comparisonTitle: "Comparação de custo de uso",
    sessionsPerMonthLabel: "Sessões por mês",
    monthlySessionsAriaLabel: "Sessões mensais",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Corra o Rejourney na sua própria infraestrutura.",
    viewSource: "Ver código-fonte",
  },
  it: {
    metaTitle: "Prezzi Rejourney: analytics mobile e session replay a prezzo fisso",
    metaDescription: "Prezzi Rejourney per analytics mobile, session replay, crash reporting, heatmap e self-hosted.",
    ogTitle: "Prezzi Rejourney: analytics mobile e session replay a prezzo fisso",
    ogDescription: "Prezzi fissi per session replay mobile, heatmap, crash, journey e analytics self-hosted.",
    twitterTitle: "Prezzi Rejourney: analytics mobile a prezzo fisso",
    pageName: "Prezzi Rejourney",
    ariaLabel: "Prezzi",
    heading: "Prezzi",
    intro: "Piani mensili fissi per session replay e analytics mobile. Scegli in base al volume di sessioni; le funzionalità principali restano incluse.",
    copied: "Copiato",
    perMonth: "al mese",
    perYear: "all'anno",
    sessionsPerMonth: (sessions) => `${sessions} replay di sessione gratis`,
    startFree: "Inizia gratis",
    getStarted: "Inizia",
    contact: "Contatto",
    comparisonTitle: "Confronto costi",
    sessionsPerMonthLabel: "Sessioni al mese",
    selfHostedHeading: "Esegui Rejourney sulla tua infrastruttura.",
    viewSource: "Vedi sorgente",
  },
  nl: {
    metaTitle: "Rejourney prijzen: mobiele analytics en sessiereplay voor vaste prijs",
    metaDescription: "Rejourney prijzen voor mobiele analytics, sessiereplay, crashrapportage, heatmaps en self-hosted deployments.",
    ogTitle: "Rejourney prijzen: mobiele analytics en sessiereplay voor vaste prijs",
    ogDescription: "Vaste prijzen voor mobiele sessiereplay, heatmaps, crashes, journeys en self-hosted analytics.",
    twitterTitle: "Rejourney prijzen: mobiele analytics voor vaste prijs",
    pageName: "Rejourney Prijzen",
    ariaLabel: "Prijzen",
    heading: "Prijzen",
    intro: "Vaste maandelijkse plannen voor mobiele sessiereplay en analytics. Kies op sessievolume; de kernfuncties blijven inbegrepen.",
    copied: "Gekopieerd",
    perMonth: "per maand",
    perYear: "per jaar",
    sessionsPerMonth: (sessions) => `${sessions} gratis sessiereplays`,
    startFree: "Start gratis",
    getStarted: "Aan de slag",
    contact: "Contact",
    comparisonTitle: "Kostenvergelijking",
    sessionsPerMonthLabel: "Sessies per maand",
    selfHostedHeading: "Draai Rejourney op je eigen infrastructuur.",
    viewSource: "Bron bekijken",
  },
  pl: {
    metaTitle: "Cennik Rejourney: mobilna analityka i session replay w stałej cenie",
    metaDescription: "Cennik Rejourney dla mobilnej analityki, session replay, crash reporting, heatmap i self-hosted.",
    ogTitle: "Cennik Rejourney: mobilna analityka i session replay w stałej cenie",
    ogDescription: "Stałe ceny dla mobile session replay, heatmap, crashy, journey i self-hosted analytics.",
    twitterTitle: "Cennik Rejourney: mobilna analityka w stałej cenie",
    pageName: "Cennik Rejourney",
    ariaLabel: "Cennik",
    heading: "Cennik",
    intro: "Stałe miesięczne plany dla mobile session replay i analytics. Wybierz według wolumenu sesji; kluczowe funkcje są wliczone.",
    copied: "Skopiowano",
    perMonth: "miesięcznie",
    perYear: "rocznie",
    sessionsPerMonth: (sessions) => `${sessions} darmowych session replays`,
    startFree: "Zacznij za darmo",
    getStarted: "Zacznij",
    contact: "Kontakt",
    comparisonTitle: "Porównanie kosztów",
    sessionsPerMonthLabel: "Sesje miesięcznie",
    selfHostedHeading: "Uruchom Rejourney na własnej infrastrukturze.",
    viewSource: "Zobacz źródło",
  },
  ru: {
    metaTitle: "Цены Rejourney: mobile analytics и session replay по фиксированной цене",
    metaDescription: "Цены Rejourney для mobile analytics, session replay, crash reporting, heatmap и self-hosted deployments.",
    ogTitle: "Цены Rejourney: mobile analytics и session replay по фиксированной цене",
    ogDescription: "Простые фиксированные цены для mobile session replay, heatmap, crash reporting, journeys и self-hosted analytics.",
    twitterTitle: "Цены Rejourney: mobile analytics по фиксированной цене",
    pageName: "Цены Rejourney",
    ariaLabel: "Цены",
    heading: "Цены",
    intro: "Фиксированные месячные планы для mobile session replay и analytics. Выбирайте по объему сессий; основные функции включены.",
    contactEyebrow: "Связаться с devs",
    contactHeading: "Нужна новая функция?",
    copied: "Скопировано",
    emailCopiedToast: "Email скопирован.",
    planDescriptions: {
      free: "Для ранних проектов и production-проверки.",
      starter: "Для приложений с регулярным трафиком.",
      growth: "Для растущих команд с большим объемом replay.",
      pro: "Для высоконагруженных приложений и зрелых мобильных команд.",
      fallback: "Для мобильных команд, которые строят с Rejourney.",
    },
    sharedFeatures: [
      "AI Replay Query Builder",
      "Crashes/ANR/Errors",
      "Growth analytics",
      "Геоаналитика",
      "Journey analytics",
      "Heat maps",
      "Неограниченные analytics/events",
      "Неограниченное хранение данных кроме replays",
    ],
    popular: "Популярно",
    perMonth: "в месяц",
    perYear: "в год",
    sessionsPerMonth: (sessions) => `${sessions} бесплатных session replays`,
    replayRetention: (retention) => `${retention} хранения replay`,
    startFree: "Начать бесплатно",
    getStarted: "Начать",
    enterpriseEyebrow: "Enterprise",
    enterpriseHeading: (sessions) => `Нужно больше ${sessions} сессий в месяц?`,
    enterpriseCopy: "Индивидуальный объем сессий, хранение replay и высокопроизводительные storage buckets.",
    contact: "Контакт",
    comparisonTitle: "Сравнение стоимости",
    comparisonSubtitle: "Фиксированная цена Rejourney против usage-based session replay.",
    sessionsPerMonthLabel: "Сессии в месяц",
    monthlySessionsAriaLabel: "Месячные сессии",
    rejourneyPlanLabel: (plan, isCustom) => `План ${plan}${isCustom ? ", индивидуальный объем" : ""}`,
    posthogEstimate: "Оценка replay по usage-based модели",
    sentryEstimate: "~$0.006 за replay add-on",
    selfHostedEyebrow: "Self-hosted",
    selfHostedHeading: "Запустите Rejourney на своей инфраструктуре.",
    selfHostedCopy: "Разверните через Docker или K3s и храните данные сессий внутри своей среды.",
    viewSource: "Смотреть исходный код",
  },
  vi: {
    metaTitle: "Giá Rejourney: mobile analytics và session replay giá cố định",
    metaDescription: "Giá Rejourney cho mobile analytics, session replay, crash reporting, heatmap và self-hosted deployments.",
    ogTitle: "Giá Rejourney: mobile analytics và session replay giá cố định",
    ogDescription: "Giá cố định cho mobile session replay, heatmap, crash reporting, journeys và self-hosted analytics.",
    twitterTitle: "Giá Rejourney: mobile analytics giá cố định",
    pageName: "Giá Rejourney",
    ariaLabel: "Giá",
    heading: "Giá",
    intro: "Các gói hàng tháng cố định cho mobile session replay và analytics. Chọn theo số phiên; bộ tính năng chính vẫn được bao gồm.",
    copied: "Đã sao chép",
    perMonth: "mỗi tháng",
    perYear: "mỗi năm",
    sessionsPerMonth: (sessions) => `${sessions} session replay miễn phí`,
    startFree: "Bắt đầu miễn phí",
    getStarted: "Bắt đầu",
    contact: "Liên hệ",
    comparisonTitle: "So sánh chi phí",
    sessionsPerMonthLabel: "Phiên mỗi tháng",
    selfHostedHeading: "Chạy Rejourney trên hạ tầng của bạn.",
    viewSource: "Xem mã nguồn",
  },
  hi: {
    metaTitle: "Rejourney Pricing: fixed-price mobile analytics और session replay",
    pageName: "Rejourney Pricing",
    ariaLabel: "Pricing",
    heading: "Pricing",
    intro: "Mobile session replay और analytics के लिए fixed monthly plans. Session volume से चुनें; core features शामिल रहते हैं.",
    copied: "Copied",
    perMonth: "प्रति माह",
    sessionsPerMonth: (sessions) => `${sessions} session replays`,
    startFree: "मुफ्त शुरू करें",
    getStarted: "शुरू करें",
    contact: "Contact",
    comparisonTitle: "Usage cost comparison",
    sessionsPerMonthLabel: "Sessions प्रति माह",
    selfHostedHeading: "Rejourney को अपनी infrastructure पर चलाएं.",
  },
  id: {
    metaTitle: "Harga Rejourney: mobile analytics dan session replay harga tetap",
    pageName: "Harga Rejourney",
    ariaLabel: "Harga",
    heading: "Harga",
    intro: "Paket bulanan tetap untuk mobile session replay dan analytics. Pilih berdasarkan volume sesi; fitur inti tetap termasuk.",
    copied: "Disalin",
    perMonth: "per bulan",
    sessionsPerMonth: (sessions) => `${sessions} session replay gratis`,
    startFree: "Mulai gratis",
    getStarted: "Mulai",
    contact: "Kontak",
    comparisonTitle: "Perbandingan biaya",
    sessionsPerMonthLabel: "Sesi per bulan",
    selfHostedHeading: "Jalankan Rejourney di infrastruktur Anda sendiri.",
  },
  ja: {
    metaTitle: "Rejourney 料金: 固定価格のモバイル分析と session replay",
    pageName: "Rejourney 料金",
    ariaLabel: "料金",
    heading: "料金",
    intro: "モバイル session replay と分析のための固定月額プラン。セッション量で選び、主要機能は含まれます。",
    copied: "コピー済み",
    perMonth: "月額",
    sessionsPerMonth: (sessions) => `${sessions} 件の無料セッションリプレイ`,
    startFree: "無料で始める",
    getStarted: "始める",
    contact: "連絡",
    comparisonTitle: "コスト比較",
    sessionsPerMonthLabel: "月間セッション",
    selfHostedHeading: "自分のインフラで Rejourney を実行できます。",
  },
  ko: {
    metaTitle: "Rejourney 가격: 고정 요금 모바일 분석과 session replay",
    pageName: "Rejourney 가격",
    ariaLabel: "가격",
    heading: "가격",
    intro: "모바일 session replay와 분석을 위한 고정 월간 플랜입니다. 세션 볼륨으로 선택하고 핵심 기능은 포함됩니다.",
    copied: "복사됨",
    perMonth: "월",
    sessionsPerMonth: (sessions) => `무료 세션 리플레이 ${sessions}건`,
    startFree: "무료로 시작",
    getStarted: "시작하기",
    contact: "문의",
    comparisonTitle: "비용 비교",
    sessionsPerMonthLabel: "월간 세션",
    selfHostedHeading: "자체 인프라에서 Rejourney를 실행하세요.",
  },
  "zh-cn": {
    metaTitle: "Rejourney 价格：固定价格的移动分析与 session replay",
    pageName: "Rejourney 价格",
    ariaLabel: "价格",
    heading: "价格",
    intro: "面向移动 session replay 和分析的固定月度套餐。按会话量选择，核心功能始终包含。",
    copied: "已复制",
    perMonth: "每月",
    sessionsPerMonth: (sessions) => `${sessions} 次免费会话回放`,
    startFree: "免费开始",
    getStarted: "开始使用",
    contact: "联系",
    comparisonTitle: "使用成本对比",
    sessionsPerMonthLabel: "每月会话数",
    selfHostedHeading: "在你自己的基础设施上运行 Rejourney。",
  },
};

const localizedDocMetadataOverrides: Partial<Record<MarketingLocaleCode, Record<string, Partial<DocMetadata>>>> = {
  ar: {
    "web/getting-started": {
      title: "Web SDK",
      category: "الويب",
      description: "ثبّت Rejourney Web SDK لإعادة تشغيل جلسات المتصفح، وتتبع الشبكة، والتقاط الأخطاء، وتحليلات المنتج عبر React وNext.js وVue وغيرها.",
      keywords: ["توثيق Web SDK", "session replay للمتصفح", "تحليلات المتصفح", "توثيق JavaScript SDK"],
    },
  },
  es: {
    "web/getting-started": {
      title: "SDK web",
      category: "Web",
      description: "Instala el SDK web de Rejourney para session replay en navegador, seguimiento de red, captura de errores y analítica de producto en React, Next.js, Vue y más.",
      keywords: ["documentación SDK web", "session replay navegador", "analítica browser", "documentación JavaScript SDK"],
    },
  },
  tr: {
    "web/getting-started": {
      title: "Web SDK",
      category: "Web",
      description: "React, Next.js, Vue ve daha fazlasında tarayıcı session replay, network takibi, hata yakalama ve ürün analitiği için Rejourney Web SDK'yı kur.",
      keywords: ["web SDK dokümantasyonu", "tarayıcı session replay", "browser analitik", "JavaScript SDK dokümantasyonu"],
    },
  },
};

export function getContentLocaleCopy(localeOrCode: MarketingLocale | MarketingLocaleCode): ContentLocaleCopy {
  const locale = typeof localeOrCode === "string" ? MARKETING_LOCALES[localeOrCode] : localeOrCode;
  const override = contentLocaleOverrides[locale.code] ?? {};

  return {
    ...englishContentCopy,
    ...override,
    pricing: {
      ...englishContentCopy.pricing,
      ...(override.pricing ?? {}),
      ...(pricingLocaleOverrides[locale.code] ?? {}),
      planDescriptions: {
        ...englishContentCopy.pricing.planDescriptions,
        ...(override.pricing?.planDescriptions ?? {}),
        ...(pricingLocaleOverrides[locale.code]?.planDescriptions ?? {}),
      },
      sharedFeatures:
        pricingLocaleOverrides[locale.code]?.sharedFeatures
        ?? override.pricing?.sharedFeatures
        ?? englishContentCopy.pricing.sharedFeatures,
    },
  };
}

export function getLocalizedDocMetadata(metadata: DocMetadata, locale: MarketingLocale): DocMetadata {
  const copy = getContentLocaleCopy(locale);
  const metadataOverride = localizedDocMetadataOverrides[locale.code]?.[metadata.path] ?? {};
  const title = metadataOverride.title ?? metadata.title;
  const category = metadataOverride.category ?? metadata.category;
  const description = metadataOverride.description
    ?? (locale.code === "en"
      ? metadata.description ?? copy.docDefaultDescription(title)
      : copy.docDefaultDescription(title));
  const keywords = Array.from(new Set([
    ...(metadata.keywords ?? []),
    ...(metadataOverride.keywords ?? []),
    ...copy.docKeywords,
  ]));

  return {
    ...metadata,
    title,
    category,
    description,
    keywords,
  };
}

export function getLocalizedArticleSeo(article: Article, locale: MarketingLocale) {
  const copy = getContentLocaleCopy(locale);
  const primaryKeyword = article.seo.primaryKeyword || article.seo.targetKeywords[0] || "mobile observability";
  const metaDescription = locale.code === "en"
    ? article.seo.metaDescription
    : copy.articleDefaultDescription(article.title, primaryKeyword);
  const readTimeMinutes = article.readTime.match(/\d+/)?.[0] ?? article.readTime;

  return {
    title: article.title,
    subtitle: article.subtitle,
    metaTitle: article.seo.metaTitle,
    metaDescription,
    targetKeywords: Array.from(new Set([...article.seo.targetKeywords, ...copy.docKeywords])),
    readTime: copy.readTime(readTimeMinutes),
  };
}
