//
//  Rejourney.h
//  Rejourney
//
//  React Native TurboModule for session recording.
//
//  Dual Architecture Support:
//  - Old Architecture: Implements RCTBridgeModule
//  - New Architecture: Implements NativeRejourneySpec (generated by Codegen)
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
//  Copyright (c) 2026 Rejourney
//

#ifndef Rejourney_Core_h
#define Rejourney_Core_h

#import <Foundation/Foundation.h>

#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#else
#import "RCTBridgeModule.h"
#endif

// New Architecture (TurboModules) support
#ifdef RCT_NEW_ARCH_ENABLED
#import <RejourneySpec/RejourneySpec.h>
#endif

NS_ASSUME_NONNULL_BEGIN

/**
 * Rejourney Native Module
 *
 * Architecture Support:
 * - Old Architecture: Conforms to RCTBridgeModule, uses RCT_EXPORT_METHOD macros
 * - New Architecture: Also conforms to NativeRejourneySpec, implements getTurboModule:
 *
 * The module automatically detects the architecture at runtime and uses
 * the appropriate communication channel (Bridge vs JSI).
 */
#ifdef RCT_NEW_ARCH_ENABLED
@interface Rejourney : NSObject <RCTBridgeModule, NativeRejourneySpec>
#else
@interface Rejourney : NSObject <RCTBridgeModule>
#endif

@end

NS_ASSUME_NONNULL_END

#endif /* Rejourney_Core_h */
