#!/usr/bin/env node
/**
 * Generate version.ts from package.json.
 * Keep this in sync with the published package version.
 */

const fs = require('fs');
const path = require('path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const versionFilePath = path.join(__dirname, '..', 'src', 'sdk', 'version.ts');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

const content = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/generate-version.cjs from package.json
 */

export const SDK_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, content);
console.log(`Synced web SDK version metadata to '${version}'`);
